theme = "onedark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
G = "goto_file_end"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "exit_select_mode"
