;; C/C++
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(defun my-c-mode-common-hook ()
  (c-set-style "stroustrup")
  (c-set-offset 'innamespace 0)
  (c-set-offset 'substatement-open 0)
  (setq c-basic-offset 4))
(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
(defun my-c++-mode-hook ()
  (setq flycheck-gcc-language-standard "c++14")
  (setq flycheck-clang-language-standard "c++14"))
(add-hook 'c++-mode-hook 'my-c++-mode-hook)
