;; Web modes
(remove-hook 'html-mode-hook 'turn-on-auto-fill)
(autoload 'web-mode "web-mode" "Web mode" t)
(add-to-list 'auto-mode-alist '("\\.json\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-jsx-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . js2-jsx-mode))
(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'" . web-mode))
(add-hook 'web-mode-hook (lambda ()
  ;;(setq web-mode-engines-alist '(("django" . "\\.html")))
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 2))
  ;; FIXME
  ;;(add-to-list 'web-mode-engine-file-regexps '("django" . "\\.html"))
)
(add-hook 'js2-mode-hook (lambda ()
  (electric-indent-local-mode 1)
  (setq js2-basic-offset 2)))
